### ISSUE TITLE
Build command does not run through: Log file 

### ISSUE THREAD

**Issue by bph** [bph/flcharity#1]
### Yesterday's error message
ERROR in ./src/edit.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
/Users/birgit/Documents/flcharity/src/edit.js: Support for the experimental syntax 'classProperties' isn't currently enabled (35:9):

  33 | export default class Edit extends Compontent {
  34 | 
> 35 |          state = {
     |                ^
  36 |                  charitynumber: "",
  37 |                  isLoading : true,
  38 |                  isSaving : false,

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
    at PoolWorker.fromErrorObj (/Users/birgit/Documents/flcharity/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/birgit/Documents/flcharity/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at Object.raise (/Users/birgit/Documents/flcharity/node_modules/@babel/parser/lib/index.js:6983:17)
    at Object.expectPlugin (/Users/birgit/Documents/flcharity/node_modules/@babel/parser/lib/index.js:8381:18)
    at Object.parseClassProperty (/Users/birgit/Documents/flcharity/node_modules/@babel/parser/lib/index.js:11673:12)

**Comment by bph** [comment]
Found a fix in this pull request: https://github.com/WordPress/gutenberg/pull/19773#issuecomment-587562543

Added "babel": {
		"presets": [
			"@wordpress/default"
		],
		"plugins": [
			"@babel/plugin-proposal-class-properties"
		]
	},

to package.json

**Comment by bph** [comment]
Also installed 
npm install @wordpress/scripts --save-dev
